window.VOCAB_DATA = [
  {
    "id": "v101",
    "word": "unlettered",
    "partOfSpeech": "adjective (বিশেষণ)",
    "bangla": "নিরক্ষর, বর্ণজ্ঞানহীন, অশিক্ষিত",
    "correctDefinition": "illiterate, not educated or knowledgeable in academic learning",
    "options": [
      "illiterate, not educated or knowledgeable in academic learning",
      "flying at high speeds in the sky",
      "having colorful feathers",
      "extremely loud and noisy"
    ],
    "example": "Once upon a time there lived a bird. It was unlettered.",
    "useCase": "Although he was unlettered, his traditional wisdom about nature was profound.",
    "textbookUseCase": "In The Parrot's Tale, the king was angry because the bird was unlettered and lived freely.",
    "synonyms": "illiterate, unschooled, untaught, uneducated, ignorant, unenlightened",
    "unitNumber": 1,
    "unit": "Unit 1: Education and Life",
    "lesson": "Lesson 1: The Parrot's Tale",
    "page": 7,
    "printedPage": 1,
    "level": "Intermediate",
    "noun": "Illiteracy / Unletteredness",
    "verb": "Letter (educate)",
    "adjective": "Unlettered / Illiterate",
    "adverb": "Unletteredly",
    "verbForms": {
      "v1_present": "letter / letters",
      "v2_past": "lettered",
      "v3_past_participle": "lettered",
      "v4_continuous": "lettering",
      "future": "will letter"
    },
    "degrees": {
      "positive": "unlettered",
      "comparative": "more unlettered",
      "superlative": "most unlettered"
    },
    "antonyms": "educated, literate, learned, scholarly, cultured, erudite"
  },
  {
    "id": "v102",
    "word": "scripture",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "ধর্মগ্রন্থ, পবিত্র শাস্ত্র",
    "correctDefinition": "sacred religious or philosophical writings considered authoritative",
    "options": [
      "sacred religious or philosophical writings considered authoritative",
      "a legal contract between merchants",
      "a type of sweet tropical fruit",
      "a golden cage for keeping birds"
    ],
    "example": "It sang but couldn't recite a word of scripture.",
    "useCase": "Scholars spend years studying ancient scripture to understand history.",
    "textbookUseCase": "The parrot was force-fed pages torn from scripture books.",
    "synonyms": "sacred text, holy book, religious canon, bible, gospel, testament",
    "unitNumber": 1,
    "unit": "Unit 1: Education and Life",
    "lesson": "Lesson 1: The Parrot's Tale",
    "page": 7,
    "printedPage": 1,
    "level": "Intermediate",
    "noun": "Scripture / Script",
    "verb": "Inscribe / Script",
    "adjective": "Scriptural / Scripted",
    "adverb": "Scripturally",
    "verbForms": {
      "v1_present": "script / scripts",
      "v2_past": "scripted",
      "v3_past_participle": "scripted",
      "v4_continuous": "scripting",
      "future": "will script"
    },
    "degrees": {
      "positive": "scriptural",
      "comparative": "more scriptural",
      "superlative": "most scriptural"
    },
    "antonyms": "profane writing, secular literature, heresy"
  },
  {
    "id": "v103",
    "word": "automated",
    "partOfSpeech": "adjective (বিশেষণ)",
    "bangla": "স্বয়ংক্রিয়, কম্পিউটারাইজড",
    "correctDefinition": "operated largely by computerized machinery or digital systems",
    "options": [
      "expensive and hard to obtain",
      "extremely slow and difficult to finish",
      "done manually by many workers",
      "operated largely by computerized machinery or digital systems"
    ],
    "example": "Routine administrative tasks in classrooms can be automated with AI.",
    "useCase": "Automated grading systems help teachers save valuable time.",
    "textbookUseCase": "AI systems automate administrative tasks in digital classrooms.",
    "synonyms": "computerized, mechanized, robotic, programmed, digital",
    "unitNumber": 1,
    "unit": "Unit 1: Education and Life",
    "lesson": "Lesson 2: Education and Technology",
    "page": 13,
    "printedPage": 7,
    "level": "Basic",
    "antonyms": "manual, handcrafted, human-operated, non-automated"
  },
  {
    "id": "v104",
    "word": "pedagogy",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "শিক্ষাদান পদ্ধতি, শিক্ষাবিজ্ঞান",
    "correctDefinition": "the method and practice of teaching, especially as an academic subject",
    "options": [
      "the financial budget of a school board",
      "the method and practice of teaching, especially as an academic subject",
      "the physical structure of school buildings",
      "the punishment given to disobedient pupils"
    ],
    "example": "Modern pedagogy emphasizes active learning rather than rote memorization.",
    "useCase": "Teachers continuously update their pedagogy to engage digital learners.",
    "textbookUseCase": "Lesson 3 explores child-centered pedagogy that nurtures natural curiosity.",
    "synonyms": "teaching method, educational theory, instructional practice, schooling",
    "unitNumber": 1,
    "unit": "Unit 1: Education and Life",
    "lesson": "Lesson 3: Children in School",
    "page": 20,
    "printedPage": 14,
    "level": "Advanced",
    "antonyms": "anti-intellectualism, uneducational method"
  },
  {
    "id": "v105",
    "word": "engagement",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "সক্রিয় অংশগ্রহণ, সামাজিক সম্পৃক্ততা",
    "correctDefinition": "active participation, involvement, or commitment to a community cause",
    "options": [
      "a formal commercial contract",
      "a state of complete silence",
      "an official military combat",
      "active participation, involvement, or commitment to a community cause"
    ],
    "example": "Civic engagement empowers citizens to contribute to community welfare.",
    "useCase": "Youth engagement is crucial for national development.",
    "textbookUseCase": "Civic engagement in Lesson 4 teaches students their civic responsibilities.",
    "synonyms": "participation, involvement, commitment, dedication, collaboration",
    "unitNumber": 1,
    "unit": "Unit 1: Education and Life",
    "lesson": "Lesson 4: Civic Engagement",
    "page": 31,
    "printedPage": 25,
    "level": "Intermediate",
    "antonyms": "disengagement, detachment, apathy, indifference, alienation"
  },
  {
    "id": "v201",
    "word": "aesthetic",
    "partOfSpeech": "adjective (বিশেষণ)",
    "bangla": "নান্দনিক, সৌন্দর্যবিষয়ক, শিল্পরুচিসম্মত",
    "correctDefinition": "concerned with beauty, artistic taste, or appreciation of art",
    "options": [
      "concerned with beauty, artistic taste, or appreciation of art",
      "destructive to nature and surroundings",
      "common and uninteresting in daily life",
      "related to mathematical calculations"
    ],
    "example": "Beauty gives us an aesthetic pleasure when we behold a work of art.",
    "useCase": "The architecture of Lalbagh Fort has great aesthetic and historical value.",
    "textbookUseCase": "In Unit 2 Lesson 1, beauty is analyzed through its aesthetic pleasure.",
    "synonyms": "artistic, beautiful, sublime, tasteful, elegant, exquisite",
    "unitNumber": 2,
    "unit": "Unit 2: Art and Craft",
    "lesson": "Lesson 1: What is Beauty?",
    "page": 36,
    "printedPage": 30,
    "level": "Advanced",
    "noun": "Aesthetics / Aesthete",
    "verb": "Aestheticize",
    "adjective": "Aesthetic / Aesthetical",
    "adverb": "Aesthetically",
    "verbForms": {
      "v1_present": "aestheticize / aestheticizes",
      "v2_past": "aestheticized",
      "v3_past_participle": "aestheticized",
      "v4_continuous": "aestheticizing",
      "future": "will aestheticize"
    },
    "degrees": {
      "positive": "aesthetic",
      "comparative": "more aesthetic",
      "superlative": "most aesthetic"
    },
    "antonyms": "unaesthetic, hideous, ugly, grotesque, tasteless, offensive"
  },
  {
    "id": "v202",
    "word": "classical",
    "partOfSpeech": "adjective (বিশেষণ)",
    "bangla": "ধ্রুপদী, চিরায়ত, শাস্ত্রীয়",
    "correctDefinition": "relating to traditional, formal music following established standard rules",
    "options": [
      "improvised on the street with simple drums",
      "created purely by computer software",
      "relating to traditional, formal music following established standard rules",
      "foreign music without any rhythm"
    ],
    "example": "Folk music is not influenced by the rules of classical music.",
    "useCase": "She has trained in classical Nazrul Geeti for over ten years.",
    "textbookUseCase": "Folk music is created naturally without following classical grammatical rules.",
    "synonyms": "traditional, formal, canonical, standard, orthodox, enduring",
    "unitNumber": 2,
    "unit": "Unit 2: Art and Craft",
    "lesson": "Lesson 2: Folk Music",
    "page": 40,
    "printedPage": 34,
    "level": "Basic",
    "noun": "Classicism / Classicist",
    "verb": "Classicize",
    "adjective": "Classical / Classic",
    "adverb": "Classically",
    "verbForms": {
      "v1_present": "classicize / classicizes",
      "v2_past": "classicized",
      "v3_past_participle": "classicized",
      "v4_continuous": "classicizing",
      "future": "will classicize"
    },
    "degrees": {
      "positive": "classical",
      "comparative": "more classical",
      "superlative": "most classical"
    },
    "antonyms": "modern, contemporary, improvised, nonstandard, unconventional"
  },
  {
    "id": "v203",
    "word": "portraiture",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "প্রতিকৃতি অঙ্কন, ব্যক্তিচিত্র শিল্প",
    "correctDefinition": "the art of making portraits, paintings, or representations of people",
    "options": [
      "the construction of wooden furniture",
      "the art of making portraits, paintings, or representations of people",
      "the writing of news articles",
      "the science of weather prediction"
    ],
    "example": "Zainul Abedin's portraiture captured the agony of the Bengal famine.",
    "useCase": "Renaissance portraiture revealed the inner psychological depth of human subjects.",
    "textbookUseCase": "Lesson 3 examines great painters and their legendary portraiture masterworks.",
    "synonyms": "portrait painting, depiction, portrayal, likeness, illustration",
    "unitNumber": 2,
    "unit": "Unit 2: Art and Craft",
    "lesson": "Lesson 3: Art",
    "page": 47,
    "printedPage": 41,
    "level": "Intermediate",
    "antonyms": "abstraction, caricature, misrepresentation"
  },
  {
    "id": "v204",
    "word": "handicraft",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "হস্তশিল্প, কারুশিল্প",
    "correctDefinition": "an activity involving making decorative or useful domestic objects by hand",
    "options": [
      "digital computer programming",
      "scientific laboratory experiments",
      "large-scale factory automation",
      "an activity involving making decorative or useful domestic objects by hand"
    ],
    "example": "Nakshi Kantha is a world-renowned traditional Bangladeshi craft.",
    "useCase": "Rural artisans earn their livelihood through authentic handicraft production.",
    "textbookUseCase": "Lesson 4 explores the heritage of Bangladeshi terracotta and woven crafts.",
    "synonyms": "artisanship, craftwork, handmade art, handiwork, crafts",
    "unitNumber": 2,
    "unit": "Unit 2: Art and Craft",
    "lesson": "Lesson 4: Craft",
    "page": 53,
    "printedPage": 47,
    "level": "Basic",
    "antonyms": "mass production, machine manufacture, industrial goods"
  },
  {
    "id": "v301",
    "word": "indigenous",
    "partOfSpeech": "adjective (বিশেষণ)",
    "bangla": "দেশীয়, আদিবাসী, স্থানীয়",
    "correctDefinition": "originating or occurring naturally in a particular place; native",
    "options": [
      "manufactured in high-tech factories",
      "unfamiliar and strange to locals",
      "originating or occurring naturally in a particular place; native",
      "imported from abroad recently"
    ],
    "example": "The indigenous myths of Bengal celebrate the power of river deities.",
    "useCase": "Protecting indigenous culture preserves vital ancestral wisdom.",
    "textbookUseCase": "Lesson 1 explores indigenous folklore rooted in rural Bengal's rivers and forests.",
    "synonyms": "native, aboriginal, endemic, homegrown, local, traditional",
    "unitNumber": 3,
    "unit": "Unit 3: Myths and Literature",
    "lesson": "Lesson 1: Myths of Bengal",
    "page": 57,
    "printedPage": 51,
    "level": "Intermediate",
    "antonyms": "foreign, alien, imported, exotic, immigrant"
  },
  {
    "id": "v302",
    "word": "labyrinth",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "গোলকধাঁধা, জটিল প্যাঁচালো পথ",
    "correctDefinition": "a complicated, confusing network of winding passages; a maze",
    "options": [
      "a tall stone tower built beside the sea",
      "a pair of wings made of bird feathers",
      "a golden crown worn by Greek rulers",
      "a complicated, confusing network of winding passages; a maze"
    ],
    "example": "King Minos had Daedalus design the fearsome Labyrinth for the Minotaur.",
    "useCase": "Navigating the labyrinth of Old Dhaka's alleys is an unforgettable adventure.",
    "textbookUseCase": "Daedalus constructed the fearsome Labyrinth on Crete to imprison the Minotaur.",
    "synonyms": "maze, tangle, web, perplexity, enigma, intricate network",
    "unitNumber": 3,
    "unit": "Unit 3: Myths and Literature",
    "lesson": "Lesson 2: Icarus",
    "page": 61,
    "printedPage": 55,
    "level": "Advanced",
    "noun": "Labyrinth",
    "verb": "Entangle / Maze",
    "adjective": "Labyrinthine / Labyrinthian",
    "adverb": "Labyrinthinely",
    "verbForms": {
      "v1_present": "entangle / entangles",
      "v2_past": "entangled",
      "v3_past_participle": "entangled",
      "v4_continuous": "entangling",
      "future": "will entangle"
    },
    "degrees": {
      "positive": "labyrinthine",
      "comparative": "more labyrinthine",
      "superlative": "most labyrinthine"
    },
    "antonyms": "straight path, direct line, simplicity, clarity"
  },
  {
    "id": "v303",
    "word": "legend",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "কিংবদন্তি, পৌরাণিক লোকগাথা",
    "correctDefinition": "a traditional story sometimes regarded as historical but unauthenticated",
    "options": [
      "a traditional story sometimes regarded as historical but unauthenticated",
      "a legal judicial verdict",
      "a modern newspaper editorial",
      "a written scientific research formula"
    ],
    "example": "The legend of Gazi Pir is celebrated across southern Bengal villages.",
    "useCase": "Many folk heroes have passed into timeless popular legend.",
    "textbookUseCase": "Lesson 3 explores how the Legend of Gazi symbolizes harmony between humans and beasts.",
    "synonyms": "myth, folklore, fable, saga, traditional tale, lore",
    "unitNumber": 3,
    "unit": "Unit 3: Myths and Literature",
    "lesson": "Lesson 3: The Legend of Gazi",
    "page": 66,
    "printedPage": 60,
    "level": "Basic",
    "antonyms": "historical fact, documented reality, nonfiction"
  },
  {
    "id": "v304",
    "word": "astrologer",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "জ্যোতিষী, গ্রহ-নক্ষত্রবিদ",
    "correctDefinition": "a person who predicts future events by studying the positions of celestial bodies",
    "options": [
      "a captain sailing trading ships",
      "a judge working in a court",
      "a physician treating human diseases",
      "a person who predicts future events by studying the positions of celestial bodies"
    ],
    "example": "Khona was married to Mihir, a prominent royal astrologer.",
    "useCase": "Ancient kings consulted the court astrologer before embarking on long voyages.",
    "textbookUseCase": "Khona's astronomical rhyming sayings guided centuries of Bengali agriculture.",
    "synonyms": "stargazer, soothsayer, seer, fortune-teller, diviner",
    "unitNumber": 3,
    "unit": "Unit 3: Myths and Literature",
    "lesson": "Lesson 4: Khona",
    "page": 68,
    "printedPage": 62,
    "level": "Basic",
    "antonyms": "astronomer (scientist), skeptic, materialist"
  },
  {
    "id": "v401",
    "word": "declaration",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "ঘোষণা, ঐতিহাসিক বিবৃতি",
    "correctDefinition": "a formal, explicit, or emphatic statement or announcement",
    "options": [
      "a commercial product advertisement",
      "a formal, explicit, or emphatic statement or announcement",
      "a secret whispered rumor",
      "a question asked in private"
    ],
    "example": "The historic 7th March speech was an immortal declaration of independence.",
    "useCase": "Bangabandhu's declaration inspired 75 million people to fight for liberation.",
    "textbookUseCase": "Unit 4 Lesson 1 analyzes the historical speeches of world-changing leaders.",
    "synonyms": "proclamation, announcement, statement, manifesto, decree",
    "unitNumber": 4,
    "unit": "Unit 4: History",
    "lesson": "Lesson 1: Three Speeches",
    "page": 71,
    "printedPage": 65,
    "level": "Intermediate",
    "noun": "Declaration / Declarer",
    "verb": "Declare",
    "adjective": "Declarative / Declared",
    "adverb": "Declaratively",
    "verbForms": {
      "v1_present": "declare / declares",
      "v2_past": "declared",
      "v3_past_participle": "declared",
      "v4_continuous": "declaring",
      "future": "will declare"
    },
    "degrees": {
      "positive": "declarative",
      "comparative": "more declarative",
      "superlative": "most declarative"
    },
    "antonyms": "secret, denial, silence, retraction, concealment"
  },
  {
    "id": "v402",
    "word": "pioneer",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "অগ্রদূত, পথিকৃৎ",
    "correctDefinition": "a person who is among the first to explore or settle a new area of thought or activity",
    "options": [
      "a guard standing at a palace gate",
      "a follower who obeys orders without question",
      "a merchant selling goods in markets",
      "a person who is among the first to explore or settle a new area of thought or activity"
    ],
    "example": "Begum Rokeya was a fearless pioneer of female education in Bengal.",
    "useCase": "She was recognized as a pioneer in medical research and women's rights.",
    "textbookUseCase": "Lesson 2 highlights great pioneering women who broke societal barriers.",
    "synonyms": "trailblazer, innovator, forerunner, trendsetter, pathfinder",
    "unitNumber": 4,
    "unit": "Unit 4: History",
    "lesson": "Lesson 2: Great Women",
    "page": 86,
    "printedPage": 80,
    "level": "Basic",
    "antonyms": "follower, imitator, conformist, disciple"
  },
  {
    "id": "v501",
    "word": "inviolable",
    "partOfSpeech": "adjective (বিশেষণ)",
    "bangla": "অলঙ্ঘনীয়, অলঙ্ঘ্য, পবিত্র",
    "correctDefinition": "never to be broken, infringed, or dishonored",
    "options": [
      "inexpensive and accessible",
      "temporary and subject to change",
      "never to be broken, infringed, or dishonored",
      "easily damaged by weather"
    ],
    "example": "Basic human rights are inviolable entitlements of every human being.",
    "useCase": "Freedom of speech is considered an inviolable constitutional right.",
    "textbookUseCase": "Unit 5 Lesson 1 examines universal and inviolable human rights declarations.",
    "synonyms": "sacred, untouchable, unbreakable, absolute, invulnerable, unassailable",
    "unitNumber": 5,
    "unit": "Unit 5: Human Rights",
    "lesson": "Lesson 1: Are We Aware of These Rights-I?",
    "page": 94,
    "printedPage": 88,
    "level": "Advanced",
    "noun": "Inviolability",
    "verb": "Violate (opposite)",
    "adjective": "Inviolable / Inviolate",
    "adverb": "Inviolably",
    "verbForms": {
      "v1_present": "violate / violates",
      "v2_past": "violated",
      "v3_past_participle": "violated",
      "v4_continuous": "violating",
      "future": "will violate"
    },
    "degrees": {
      "positive": "inviolable",
      "comparative": "more inviolable",
      "superlative": "most inviolable"
    },
    "antonyms": "violable, fragile, vulnerable, revocable, breachable"
  },
  {
    "id": "v502",
    "word": "discrimination",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "বৈষম্য, ভেদাভেদ",
    "correctDefinition": "the unjust or prejudicial treatment of different categories of people",
    "options": [
      "a fair sports competition",
      "a festive cultural ceremony",
      "the unjust or prejudicial treatment of different categories of people",
      "the equal distribution of wealth"
    ],
    "example": "Universal declarations forbid racial and gender discrimination in society.",
    "useCase": "Laws must protect all citizens against discrimination in employment.",
    "textbookUseCase": "Lesson 2 highlights the struggle to eliminate racial discrimination globally.",
    "synonyms": "prejudice, bias, bigotry, intolerance, inequity, partiality",
    "unitNumber": 5,
    "unit": "Unit 5: Human Rights",
    "lesson": "Lesson 2: Are We Aware of These Rights-II?",
    "page": 99,
    "printedPage": 93,
    "level": "Basic",
    "noun": "Discrimination",
    "verb": "Discriminate",
    "adjective": "Discriminatory / Discriminating",
    "adverb": "Discriminatorily",
    "verbForms": {
      "v1_present": "discriminate / discriminates",
      "v2_past": "discriminated",
      "v3_past_participle": "discriminated",
      "v4_continuous": "discriminating",
      "future": "will discriminate"
    },
    "degrees": {
      "positive": "discriminatory",
      "comparative": "more discriminatory",
      "superlative": "most discriminatory"
    },
    "antonyms": "equality, fairness, impartiality, justice, tolerance, neutrality"
  },
  {
    "id": "v503",
    "word": "entitlement",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "ন্যায্য অধিকার, প্রাপ্যতা",
    "correctDefinition": "the fact of having a right to something; a just legal claim",
    "options": [
      "the fact of having a right to something; a just legal claim",
      "a voluntary charitable gift",
      "a harsh monetary penalty",
      "an accidental discovery"
    ],
    "example": "Healthcare and primary education are basic citizen entitlements.",
    "useCase": "Every child has an entitlement to free and quality education.",
    "textbookUseCase": "Lesson 3 explains fundamental entitlements regarding health and literacy.",
    "synonyms": "right, prerogative, claim, privilege, legal due",
    "unitNumber": 5,
    "unit": "Unit 5: Human Rights",
    "lesson": "Lesson 3: Rights to Health and Education",
    "page": 100,
    "printedPage": 94,
    "level": "Intermediate",
    "noun": "Entitlement",
    "verb": "Entitle",
    "adjective": "Entitled",
    "adverb": "Entitledly",
    "verbForms": {
      "v1_present": "entitle / entitles",
      "v2_past": "entitled",
      "v3_past_participle": "entitled",
      "v4_continuous": "entitling",
      "future": "will entitle"
    },
    "degrees": {
      "positive": "entitled",
      "comparative": "more entitled",
      "superlative": "most entitled"
    },
    "antonyms": "disqualification, prohibition, ban, denial"
  },
  {
    "id": "v504",
    "word": "hazardous",
    "partOfSpeech": "adjective (বিশেষণ)",
    "bangla": "বিপজ্জনক, ঝুঁকিপূর্ণ",
    "correctDefinition": "risky; dangerous to health and safety",
    "options": [
      "clean and highly sanitary",
      "profitable with no risk",
      "risky; dangerous to health and safety",
      "comfortable and relaxing"
    ],
    "example": "Coal miners work in hazardous subterranean tunnels for long hours.",
    "useCase": "Protective equipment is mandatory when working with hazardous chemicals.",
    "textbookUseCase": "Lesson 4 depicts the grueling and hazardous lives of underground coal miners.",
    "synonyms": "perilous, dangerous, treacherous, unsafe, precarious, risky",
    "unitNumber": 5,
    "unit": "Unit 5: Human Rights",
    "lesson": "Lesson 4: Coal Miners",
    "page": 102,
    "printedPage": 96,
    "level": "Basic",
    "noun": "Hazard",
    "verb": "Hazard (risk)",
    "adjective": "Hazardous",
    "adverb": "Hazardously",
    "verbForms": {
      "v1_present": "hazard / hazards",
      "v2_past": "hazarded",
      "v3_past_participle": "hazarded",
      "v4_continuous": "hazarding",
      "future": "will hazard"
    },
    "degrees": {
      "positive": "hazardous",
      "comparative": "more hazardous",
      "superlative": "most hazardous"
    },
    "antonyms": "safe, secure, harmless, protected, risk-free"
  },
  {
    "id": "v505",
    "word": "abolitionist",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "দাসপ্রথা উচ্ছেদকারী, বিলোপবাদী",
    "correctDefinition": "a person who favored the legal abolition of slavery in the 19th century",
    "options": [
      "a person who favored the legal abolition of slavery in the 19th century",
      "a farmer who grew cotton",
      "a trader who sold slaves in markets",
      "a captain of a royal navy ship"
    ],
    "example": "Frederick Douglass was an escaped slave who became an eloquent abolitionist leader.",
    "useCase": "The abolitionist movement fought tirelessly to end human trafficking and slavery.",
    "textbookUseCase": "Lesson 5 details Frederick Douglass's courageous life as an abolitionist orator.",
    "synonyms": "emancipator, liberator, anti-slavery advocate, reformer",
    "unitNumber": 5,
    "unit": "Unit 5: Human Rights",
    "lesson": "Lesson 5: Frederick Douglass",
    "page": 108,
    "printedPage": 102,
    "level": "Intermediate",
    "noun": "Abolition / Abolitionist",
    "verb": "Abolish",
    "adjective": "Abolitionist / Abolished",
    "adverb": "Abolitionistically",
    "verbForms": {
      "v1_present": "abolish / abolishes",
      "v2_past": "abolished",
      "v3_past_participle": "abolished",
      "v4_continuous": "abolishing",
      "future": "will abolish"
    },
    "degrees": {
      "positive": "reformative",
      "comparative": "more reformative",
      "superlative": "most reformative"
    },
    "antonyms": "enslaver, oppressor, pro-slavery advocate"
  },
  {
    "id": "v601",
    "word": "hallucination",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "মতিভ্রম, অলীক প্রত্যক্ষ",
    "correctDefinition": "an experience involving the apparent perception of something not present",
    "options": [
      "a deep dreamless sleep",
      "a logical mathematical proof",
      "an experience involving the apparent perception of something not present",
      "a photograph printed on glossy paper"
    ],
    "example": "Scientists debate whether dreams are random neurological hallucinations.",
    "useCase": "Severe fever and dehydration can cause vivid hallucinations.",
    "textbookUseCase": "Unit 6 Lesson 1 explores psychological theories of dreams and cognitive images.",
    "synonyms": "delusion, illusion, phantom, mirage, vision, fantasy",
    "unitNumber": 6,
    "unit": "Unit 6: Dreams",
    "lesson": "Lesson 1: What is a Dream?",
    "page": 110,
    "printedPage": 104,
    "level": "Advanced",
    "antonyms": "reality, actuality, objective fact, truth"
  },
  {
    "id": "v602",
    "word": "reverie",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "দিবাস্বপ্ন, চিন্তামগ্ন ভাব",
    "correctDefinition": "a state of being pleasantly lost in one's thoughts; a daydream",
    "options": [
      "a noisy argument in the street",
      "a state of being pleasantly lost in one's thoughts; a daydream",
      "a fast running competition",
      "a violent nightmare causing fear"
    ],
    "example": "He was startled out of his quiet reverie by the ringing bell.",
    "useCase": "Poets often find artistic inspiration while lost in gentle reverie.",
    "textbookUseCase": "Dreams in Literature (Lesson 2) analyzes poetic reveries of romantic writers.",
    "synonyms": "daydream, trance, musing, brown study, contemplation",
    "unitNumber": 6,
    "unit": "Unit 6: Dreams",
    "lesson": "Lesson 2: Dreams in Literature",
    "page": 115,
    "printedPage": 109,
    "level": "Intermediate",
    "antonyms": "alertness, attentiveness, reality, mindfulness"
  },
  {
    "id": "v701",
    "word": "endurance",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "সহনশীলতা, ধৈর্য ও সহ্যক্ষমতা",
    "correctDefinition": "the ability to withstand hardship, adversity, or sustained physical exertion",
    "options": [
      "the speed of a racing sports car",
      "the volume of recorded audio",
      "the ability to withstand hardship, adversity, or sustained physical exertion",
      "the brightness of morning sunlight"
    ],
    "example": "Brojen Das demonstrated superhuman physical endurance while crossing the Channel.",
    "useCase": "Marathon runners require immense mental and bodily endurance.",
    "textbookUseCase": "Brojen Das crossed the stormy English Channel six times through heroic endurance.",
    "synonyms": "stamina, resilience, perseverance, fortitude, tolerance, grit",
    "unitNumber": 7,
    "unit": "Unit 7: Youthful Achievers",
    "lesson": "Lesson 1: Brojen Das: On Crossing the English Channel",
    "page": 120,
    "printedPage": 114,
    "level": "Intermediate",
    "noun": "Endurance",
    "verb": "Endure",
    "adjective": "Enduring / Endurable",
    "adverb": "Enduringly",
    "verbForms": {
      "v1_present": "endure / endures",
      "v2_past": "endured",
      "v3_past_participle": "endured",
      "v4_continuous": "enduring",
      "future": "will endure"
    },
    "degrees": {
      "positive": "enduring",
      "comparative": "more enduring",
      "superlative": "most enduring"
    },
    "antonyms": "fragility, weakness, vulnerability, exhaustion, surrender"
  },
  {
    "id": "v702",
    "word": "summit",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "চূড়া, শীর্ষবিন্দু",
    "correctDefinition": "the highest point of a mountain peak; the pinnacle of achievement",
    "options": [
      "a fast-flowing river current",
      "the deep base of an ocean valley",
      "the highest point of a mountain peak; the pinnacle of achievement",
      "a dense jungle in the plains"
    ],
    "example": "Musa Ibrahim hoisted the red-green flag on the summit of Mount Everest.",
    "useCase": "Reaching the mountain summit demanded days of grueling climbs.",
    "textbookUseCase": "Lesson 2 narrates the courageous Bangladeshi mountaineers scaling Himalayan summits.",
    "synonyms": "peak, apex, pinnacle, crest, zenith, top",
    "unitNumber": 7,
    "unit": "Unit 7: Youthful Achievers",
    "lesson": "Lesson 2: Scaling a Mountain Peak",
    "page": 126,
    "printedPage": 120,
    "level": "Basic",
    "antonyms": "base, bottom, nadir, valley, foot"
  },
  {
    "id": "v703",
    "word": "unbeaten",
    "partOfSpeech": "adjective (বিশেষণ)",
    "bangla": "অপরাজিত, বিজয়ী",
    "correctDefinition": "not defeated in a competition; unconquered",
    "options": [
      "tired and unable to play",
      "lost in a distant village",
      "broken into small pieces",
      "not defeated in a competition; unconquered"
    ],
    "example": "The Bangladesh women's football team remained unbeaten throughout the championship.",
    "useCase": "The team finished the season as the proud, unbeaten league champions.",
    "textbookUseCase": "Lesson 3 celebrates the girls of Kalsindur who achieved an unbeaten football streak.",
    "synonyms": "undefeated, triumphant, victorious, unvanquished, champion",
    "unitNumber": 7,
    "unit": "Unit 7: Youthful Achievers",
    "lesson": "Lesson 3: The Unbeaten Girls",
    "page": 127,
    "printedPage": 121,
    "level": "Basic",
    "noun": "Invincibility / Victory",
    "verb": "Beat (defeat)",
    "adjective": "Unbeaten / Undefeated",
    "adverb": "Unbeatenly",
    "verbForms": {
      "v1_present": "beat / beats",
      "v2_past": "beat",
      "v3_past_participle": "beaten",
      "v4_continuous": "beating",
      "future": "will beat"
    },
    "degrees": {
      "positive": "victorious",
      "comparative": "more victorious",
      "superlative": "most victorious"
    },
    "antonyms": "defeated, beaten, conquered, lost, subjugated"
  },
  {
    "id": "v801",
    "word": "kinship",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "রক্তের সম্পর্ক, আত্মীয়তা",
    "correctDefinition": "a sharing of characteristics or origins; blood relationship or family ties",
    "options": [
      "a commercial business partnership",
      "a political rivalry between candidates",
      "a sharing of characteristics or origins; blood relationship or family ties",
      "a geographic distance between towns"
    ],
    "example": "Family bonds and kinship provide lifelong emotional security.",
    "useCase": "In traditional rural communities, strong kinship ties ensure mutual help.",
    "textbookUseCase": "Lesson 1 explores how modern lifestyle impacts traditional family kinship.",
    "synonyms": "relationship, family ties, blood relation, affinity, alliance",
    "unitNumber": 8,
    "unit": "Unit 8: Relationships",
    "lesson": "Lesson 1: Family Relationship",
    "page": 132,
    "printedPage": 126,
    "level": "Intermediate",
    "antonyms": "strangeness, detachment, alienation, disconnection"
  },
  {
    "id": "v802",
    "word": "cordial",
    "partOfSpeech": "adjective (বিশেষণ)",
    "bangla": "আন্তরিক, উষ্ণ, হৃদ্যতাপূর্ণ",
    "correctDefinition": "warm and friendly; sincere in affection",
    "options": [
      "angry and confrontational",
      "warm and friendly; sincere in affection",
      "completely indifferent and quiet",
      "cold and unfriendly toward guests"
    ],
    "example": "A cordial relationship between neighbors fosters a peaceful community.",
    "useCase": "The host extended a cordial welcome to all international delegates.",
    "textbookUseCase": "Lesson 2 highlights the warmth and cordial empathy that sustain human connections.",
    "synonyms": "warm, friendly, hospitable, hearty, affectionate, genial",
    "unitNumber": 8,
    "unit": "Unit 8: Relationships",
    "lesson": "Lesson 2: Warmth in Relationships",
    "page": 135,
    "printedPage": 129,
    "level": "Basic",
    "antonyms": "cold, hostile, unfriendly, distant, antagonistic, aloof"
  },
  {
    "id": "v803",
    "word": "integrity",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "সততা, নীতিপরায়ণতা, নিখুঁত চরিত্র",
    "correctDefinition": "the quality of being honest and having strong moral principles",
    "options": [
      "extreme wealth and luxury",
      "the quality of being honest and having strong moral principles",
      "great physical strength and endurance",
      "the ability to run very fast"
    ],
    "example": "Jerry possessed an instinctive integrity that made him reliable.",
    "useCase": "A true leader inspires people through unwavering personal integrity.",
    "textbookUseCase": "Jerry possessed an instinctive integrity that refused to take unearned praise.",
    "synonyms": "honesty, uprightness, probity, morality, sincerity, honor",
    "unitNumber": 8,
    "unit": "Unit 8: Relationships",
    "lesson": "Lesson 3: A Mother in Mannville",
    "page": 144,
    "printedPage": 138,
    "level": "Advanced",
    "noun": "Integrity / Integrator",
    "verb": "Integrate",
    "adjective": "Integral / Integrated / Honest",
    "adverb": "Integrally / Honestly",
    "verbForms": {
      "v1_present": "integrate / integrates",
      "v2_past": "integrated",
      "v3_past_participle": "integrated",
      "v4_continuous": "integrating",
      "future": "will integrate"
    },
    "degrees": {
      "positive": "honest",
      "comparative": "more honest",
      "superlative": "most honest"
    },
    "antonyms": "dishonesty, corruption, deceit, duplicity, treachery, fraud"
  },
  {
    "id": "v804",
    "word": "compassion",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "সহমর্মিতা, গভীর দয়া ও ভালোবাসা",
    "correctDefinition": "sympathetic pity and concern for the sufferings or misfortunes of others",
    "options": [
      "the fear of dark and unknown places",
      "pride in one's personal achievements",
      "the desire to control others by force",
      "sympathetic pity and concern for the sufferings or misfortunes of others"
    ],
    "example": "True love is expressed through selfless compassion and kindness.",
    "useCase": "Volunteers served the flood victims with deep compassion and love.",
    "textbookUseCase": "Lesson 4 explores the philosophical essence of love and unconditional compassion.",
    "synonyms": "empathy, kindness, benevolence, mercy, sympathy, warmth",
    "unitNumber": 8,
    "unit": "Unit 8: Relationships",
    "lesson": "Lesson 4: Love",
    "page": 148,
    "printedPage": 142,
    "level": "Basic",
    "antonyms": "cruelty, ruthlessness, coldness, callousness, indifference"
  },
  {
    "id": "v901",
    "word": "transition",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "রূপান্তর, পরিবর্তনের পর্যায়",
    "correctDefinition": "the process or a period of changing from one state or condition to another",
    "options": [
      "a holiday celebrated once a year",
      "the process or a period of changing from one state or condition to another",
      "an unexpected car accident",
      "a permanent unchanging situation"
    ],
    "example": "Adolescence is a vital transition period from childhood to adulthood.",
    "useCase": "The transition to college life can be both exciting and challenging.",
    "textbookUseCase": "Unit 9 Lesson 1 highlights psychological and physical transitions of youth.",
    "synonyms": "transformation, conversion, passage, shift, changeover, evolution",
    "unitNumber": 9,
    "unit": "Unit 9: Adolescence",
    "lesson": "Lesson 1: Storms and Stresses of Adolescence",
    "page": 155,
    "printedPage": 149,
    "level": "Intermediate",
    "antonyms": "stagnation, permanence, immobility, stability"
  },
  {
    "id": "v902",
    "word": "malnutrition",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "অপুষ্টি, পুষ্টিহীনতা",
    "correctDefinition": "lack of proper nutrition, caused by not having enough to eat or not eating right food",
    "options": [
      "lack of proper nutrition, caused by not having enough to eat or not eating right food",
      "excessive consumption of fresh fruits",
      "an injury sustained while playing sports",
      "a contagious viral illness"
    ],
    "example": "Adolescent girls in rural areas often suffer from chronic malnutrition.",
    "useCase": "School feeding programs help reduce child malnutrition significantly.",
    "textbookUseCase": "Lesson 2 addresses severe malnutrition and reproductive health challenges in Bangladesh.",
    "synonyms": "undernourishment, dietary deficiency, starvation, emaciation",
    "unitNumber": 9,
    "unit": "Unit 9: Adolescence",
    "lesson": "Lesson 2: Adolescence and Some (Related) Problems in Bangladesh",
    "page": 157,
    "printedPage": 151,
    "level": "Basic",
    "antonyms": "nourishment, healthy nutrition, balanced diet"
  },
  {
    "id": "v903",
    "word": "empowerment",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "ক্ষমতায়ন, আত্মনির্ভরশীলতা",
    "correctDefinition": "the process of becoming stronger and more confident, especially in controlling one's life",
    "options": [
      "the loss of rights and personal freedom",
      "the process of becoming stronger and more confident, especially in controlling one's life",
      "financial bankruptcy of a business",
      "physical illness requiring hospitalization"
    ],
    "example": "Shilpi's story showcases the transformative power of female empowerment.",
    "useCase": "Female education leads to widespread economic and social empowerment.",
    "textbookUseCase": "In Lesson 3, Shilpi joins a youth empowerment club to resist child marriage.",
    "synonyms": "enablement, authorization, emancipation, self-determination",
    "unitNumber": 9,
    "unit": "Unit 9: Adolescence",
    "lesson": "Lesson 3: The Story of Shilpi",
    "page": 162,
    "printedPage": 156,
    "level": "Intermediate",
    "antonyms": "disempowerment, oppression, subjugation, helplessness"
  },
  {
    "id": "v904",
    "word": "intimidation",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "ভীতি প্রদর্শন, ধমকানো",
    "correctDefinition": "the action of intimidating or scaring someone, especially to force them into doing something",
    "options": [
      "a peaceful meditation session",
      "a cheerful greeting between close friends",
      "the action of intimidating or scaring someone, especially to force them into doing something",
      "the celebration of a birthday"
    ],
    "example": "Schools must enforce strict zero-tolerance policies against bullying and intimidation.",
    "useCase": "No student should suffer in silence from peer intimidation.",
    "textbookUseCase": "Lesson 4 teaches students how to recognize cyberbullying and stand up against intimidation.",
    "synonyms": "bullying, harassment, coercion, menace, terrorization, threat",
    "unitNumber": 9,
    "unit": "Unit 9: Adolescence",
    "lesson": "Lesson 4: Say 'No' to Bullying",
    "page": 167,
    "printedPage": 161,
    "level": "Basic",
    "antonyms": "encouragement, support, comfort, reassurance, protection"
  },
  {
    "id": "v1001",
    "word": "hospitality",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "আতিথেয়তা, অতিথি সেবা",
    "correctDefinition": "the friendly and generous reception and entertainment of guests or strangers",
    "options": [
      "the medical care provided in hospitals",
      "the construction of highway roads",
      "the friendly and generous reception and entertainment of guests or strangers",
      "the sale of household electronics"
    ],
    "example": "Traditional Bangladeshi culture is celebrated for its warm hospitality.",
    "useCase": "Foreign travelers were deeply touched by the village hospitality.",
    "textbookUseCase": "Lesson 1 illustrates varying manners and hospitality customs across different cultures.",
    "synonyms": "welcoming, friendliness, generosity, warmth, cordiality",
    "unitNumber": 10,
    "unit": "Unit 10: Lifestyle",
    "lesson": "Lesson 1: Manners around the World",
    "page": 177,
    "printedPage": 171,
    "level": "Basic",
    "antonyms": "hostility, inhospitality, coldness, rejection"
  },
  {
    "id": "v1002",
    "word": "etiquette",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "শিষ্টাচার, ভদ্রতা, সামাজিক রীতিনীতি",
    "correctDefinition": "the customary code of polite behavior in society or among members of a profession",
    "options": [
      "the customary code of polite behavior in society or among members of a profession",
      "a written recipe for cooking dishes",
      "a type of physical gymnastic exercise",
      "a ticket for traveling on airplanes"
    ],
    "example": "Practicing good etiquette shows respect to peers and elders.",
    "useCase": "Netiquette is the etiquette required when communicating online on social media.",
    "textbookUseCase": "Lesson 2 contrasts face-to-face etiquette with modern digital netiquette.",
    "synonyms": "manners, decorum, courtesy, propriety, protocol, civility",
    "unitNumber": 10,
    "unit": "Unit 10: Lifestyle",
    "lesson": "Lesson 2: Etiquette Netiquette",
    "page": 184,
    "printedPage": 178,
    "level": "Intermediate",
    "antonyms": "rudeness, impoliteness, discourtesy, vulgarity, bad manners"
  },
  {
    "id": "v1003",
    "word": "gastronomy",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "রন্ধনশিল্প, ভোজনসংস্কৃতি",
    "correctDefinition": "the practice or art of choosing, cooking, and eating good food",
    "options": [
      "the study of rocks and earthquakes",
      "the practice or art of choosing, cooking, and eating good food",
      "the management of commercial airports",
      "the repair of motor vehicle engines"
    ],
    "example": "Panta Ilish and Bhorta are signature staples of Bengali gastronomy.",
    "useCase": "Culinary tourism introduces travelers to authentic national gastronomy.",
    "textbookUseCase": "Lesson 3 explores how food traditions and gastronomy reflect cultural identity.",
    "synonyms": "culinary art, cooking heritage, cuisine, gourmet dining",
    "unitNumber": 10,
    "unit": "Unit 10: Lifestyle",
    "lesson": "Lesson 3: Food and Culture",
    "page": 187,
    "printedPage": 181,
    "level": "Advanced",
    "noun": "Gastronomy / Gastronome",
    "verb": "Dine / Cook",
    "adjective": "Gastronomic / Gastronomical",
    "adverb": "Gastronomically",
    "verbForms": {
      "v1_present": "dine / dines",
      "v2_past": "dined",
      "v3_past_participle": "dined",
      "v4_continuous": "dining",
      "future": "will dine"
    },
    "degrees": {
      "positive": "gastronomic",
      "comparative": "more gastronomic",
      "superlative": "most gastronomic"
    },
    "antonyms": "fast food, unrefined diet"
  },
  {
    "id": "v1004",
    "word": "cardiovascular",
    "partOfSpeech": "adjective (বিশেষণ)",
    "bangla": "হৃদযন্ত্র ও রক্তনালী সংক্রান্ত",
    "correctDefinition": "relating to the heart and blood vessels",
    "options": [
      "relating to the human digestive stomach",
      "relating to the heart and blood vessels",
      "relating to eyesight and vision",
      "relating to bones and joints"
    ],
    "example": "Brisk walking and cycling improve cardiovascular fitness.",
    "useCase": "Aerobic workouts strengthen the cardiovascular system against heart disease.",
    "textbookUseCase": "Lesson 4 emphasizes regular exercise for optimal cardiovascular and mental fitness.",
    "synonyms": "circulatory, cardiac, heart-related, vascular",
    "unitNumber": 10,
    "unit": "Unit 10: Lifestyle",
    "lesson": "Lesson 4: Fitness",
    "page": 191,
    "printedPage": 185,
    "level": "Intermediate",
    "antonyms": "non-circulatory"
  },
  {
    "id": "v1005",
    "word": "consumerism",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "ভোগবাদ, অতিরিক্ত পণ্য কেনার প্রবণতা",
    "correctDefinition": "the preoccupation of society with the acquisition of consumer goods",
    "options": [
      "the study of astronomy and planets",
      "the preoccupation of society with the acquisition of consumer goods",
      "the preservation of ancient forests",
      "a medical technique for treating diseases"
    ],
    "example": "Excessive consumerism leads to environmental waste and materialism.",
    "useCase": "Critics argue that consumerism encourages people to buy items they do not need.",
    "textbookUseCase": "Lesson 5 examines the psychological and economic impact of modern consumerism.",
    "synonyms": "materialism, overconsumption, commercialism, acquisitiveness",
    "unitNumber": 10,
    "unit": "Unit 10: Lifestyle",
    "lesson": "Lesson 5: Consumerism",
    "page": 196,
    "printedPage": 190,
    "level": "Advanced",
    "antonyms": "asceticism, minimalism, conservation, simplicity"
  },
  {
    "id": "v1101",
    "word": "reconciliation",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "পুনর্মিলন, সমঝোতা, শান্তি স্থাপন",
    "correctDefinition": "the restoration of friendly relations after a dispute or war",
    "options": [
      "the construction of a border wall",
      "a legal penalty imposed on criminals",
      "the outbreak of a violent revolution",
      "the restoration of friendly relations after a dispute or war"
    ],
    "example": "Truth and reconciliation commissions help post-war societies heal.",
    "useCase": "Both conflicting parties agreed to dialogue for peaceful reconciliation.",
    "textbookUseCase": "Unit 11 analyzes how literature advocates for peace and reconciliation.",
    "synonyms": "peacemaking, pacification, resolution, appeasement, reunion",
    "unitNumber": 11,
    "unit": "Unit 11: Peace and Conflict",
    "lesson": "Lesson 1: Situations of Conflict",
    "page": 199,
    "printedPage": 193,
    "level": "Advanced",
    "noun": "Reconciliation / Reconciler",
    "verb": "Reconcile",
    "adjective": "Reconciled / Reconciliatory",
    "adverb": "Reconciliatorily",
    "verbForms": {
      "v1_present": "reconcile / reconciles",
      "v2_past": "reconciled",
      "v3_past_participle": "reconciled",
      "v4_continuous": "reconciling",
      "future": "will reconcile"
    },
    "degrees": {
      "positive": "peaceful",
      "comparative": "more peaceful",
      "superlative": "most peaceful"
    },
    "antonyms": "conflict, dispute, warfare, alienation, hostility"
  },
  {
    "id": "v1102",
    "word": "evacuation",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "স্থানান্তর, নিরাপদ স্থানে সরিয়ে নেওয়া",
    "correctDefinition": "the removal of persons from a dangerous zone to safety",
    "options": [
      "the manufacturing of heavy weapons",
      "the election of local town mayors",
      "the removal of persons from a dangerous zone to safety",
      "the arrival of foreign tourist ships"
    ],
    "example": "The old man sat beside the road during the wartime civilian evacuation.",
    "useCase": "The government ordered the immediate evacuation of coastal villagers before the cyclone.",
    "textbookUseCase": "In Ernest Hemingway's 'The Old Man at the Bridge', the old man is displaced by evacuation.",
    "synonyms": "withdrawal, relocation, clearance, departure, rescue",
    "unitNumber": 11,
    "unit": "Unit 11: Peace and Conflict",
    "lesson": "Lesson 2: \"The Old Man at the Bridge\" by Ernest Hemingway",
    "page": 203,
    "printedPage": 197,
    "level": "Intermediate",
    "antonyms": "occupation, arrival, influx, settlement"
  },
  {
    "id": "v1103",
    "word": "besieged",
    "partOfSpeech": "adjective (বিশেষণ)",
    "bangla": "অবরুদ্ধ, চারপাশ থেকে ঘেরাও করা",
    "correctDefinition": "surrounded by armed forces aiming to capture or force surrender",
    "options": [
      "protected in a luxury hotel",
      "surrounded by armed forces aiming to capture or force surrender",
      "swimming in open rivers",
      "freely traveling across borders"
    ],
    "example": "Civilians in besieged territories suffer from extreme shortages of food and medicine.",
    "useCase": "Humanitarian corridors are vital to relieve besieged cities.",
    "textbookUseCase": "Lesson 3 shares powerful firsthand testimonies from besieged communities in Gaza.",
    "synonyms": "blockaded, trapped, encircled, surrounded, under siege",
    "unitNumber": 11,
    "unit": "Unit 11: Peace and Conflict",
    "lesson": "Lesson 3: Stories From Gaza",
    "page": 208,
    "printedPage": 202,
    "level": "Intermediate",
    "antonyms": "free, liberated, relieved, unhindered"
  },
  {
    "id": "v1104",
    "word": "fraternity",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "ভ্রাতৃত্ববোধ, পারস্পরিক সৌহার্দ্য",
    "correctDefinition": "a feeling of friendship and mutual support within a group; brotherhood",
    "options": [
      "commercial rivalry between companies",
      "intense military competition between nations",
      "the destruction of historical monuments",
      "a feeling of friendship and mutual support within a group; brotherhood"
    ],
    "example": "Literature inspires global fraternity and universal brotherhood.",
    "useCase": "The United Nations was founded on principles of global peace and human fraternity.",
    "textbookUseCase": "Lesson 4 explores how world poems cultivate harmony, empathy, and human fraternity.",
    "synonyms": "brotherhood, solidarity, comradeship, fellowship, kinship",
    "unitNumber": 11,
    "unit": "Unit 11: Peace and Conflict",
    "lesson": "Lesson 4: Peace in Literature",
    "page": 214,
    "printedPage": 208,
    "level": "Basic",
    "antonyms": "hostility, rivalry, animosity, conflict"
  },
  {
    "id": "v1105",
    "word": "photojournalism",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "আলোকচিত্র সাংবাদিকতা",
    "correctDefinition": "the communicating of news and truth by means of recorded photographs",
    "options": [
      "broadcasting radio signals",
      "editing audio podcast episodes",
      "the communicating of news and truth by means of recorded photographs",
      "painting fictional abstract canvases"
    ],
    "example": "Impactful photojournalism exposes the human cost of armed conflicts.",
    "useCase": "The award-winning photojournalism piece mobilized global famine aid.",
    "textbookUseCase": "Lesson 5 examines iconic historical photographs that shaped global public opinion.",
    "synonyms": "visual journalism, documentary photography, news reportage",
    "unitNumber": 11,
    "unit": "Unit 11: Peace and Conflict",
    "lesson": "Lesson 5: Opinions through Images",
    "page": 219,
    "printedPage": 213,
    "level": "Intermediate",
    "antonyms": "fiction, studio staging"
  },
  {
    "id": "v1201",
    "word": "contamination",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "দূষণ, বিষাক্ত পদার্থের সংমিশ্রণ",
    "correctDefinition": "the action or state of making something impure by polluting or poisoning",
    "options": [
      "the construction of river bridges",
      "the action or state of making something impure by polluting or poisoning",
      "the purification of clean mountain water",
      "the planting of roadside trees"
    ],
    "example": "Industrial waste caused severe chemical contamination in the Buriganga river.",
    "useCase": "Water contamination leads to waterborne epidemics in flood-affected regions.",
    "textbookUseCase": "Lesson 1 examines severe water pollution and toxic contamination threatening rivers.",
    "synonyms": "pollution, poisoning, impurity, taint, infection, toxicity",
    "unitNumber": 12,
    "unit": "Unit 12: Environment and Nature",
    "lesson": "Lesson 1: Water, Water Everywhere...",
    "page": 224,
    "printedPage": 218,
    "level": "Basic",
    "noun": "Contamination / Contaminant",
    "verb": "Contaminate",
    "adjective": "Contaminated / Contaminating",
    "adverb": "Contaminatedly",
    "verbForms": {
      "v1_present": "contaminate / contaminates",
      "v2_past": "contaminated",
      "v3_past_participle": "contaminated",
      "v4_continuous": "contaminating",
      "future": "will contaminate"
    },
    "degrees": {
      "positive": "polluted",
      "comparative": "more polluted",
      "superlative": "most polluted"
    },
    "antonyms": "purification, cleanliness, sterilization, decontamination"
  },
  {
    "id": "v1202",
    "word": "activist",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "সক্রিয় কর্মী, আন্দোলনকারী, সমাজকর্মী",
    "correctDefinition": "a person who campaigns to bring about political or social change",
    "options": [
      "a spectator sitting silently in a meeting",
      "a person who campaigns to bring about political or social change",
      "a person who avoids public gatherings",
      "a factory manager producing plastic products"
    ],
    "example": "Greta Thunberg became a globally recognized climate activist as a teenager.",
    "useCase": "Environmental activists urged governments to reduce greenhouse gas emissions.",
    "textbookUseCase": "Unit 12 showcases youth activists fighting for biodiversity and clean oceans.",
    "synonyms": "campaigner, advocate, reformer, champion, crusader",
    "unitNumber": 12,
    "unit": "Unit 12: Environment and Nature",
    "lesson": "Lesson 2: The Greta Effect",
    "page": 227,
    "printedPage": 221,
    "level": "Basic",
    "antonyms": "passivist, bystander, conformist, silent observer"
  },
  {
    "id": "v1203",
    "word": "endangered",
    "partOfSpeech": "adjective (বিশেষণ)",
    "bangla": "বিপন্ন, বিলুপ্তির ঝুঁকিতে থাকা",
    "correctDefinition": "at serious risk of extinction in the wild",
    "options": [
      "harmful to human agriculture",
      "safely kept inside home aquariums",
      "living in high numbers in forests",
      "at serious risk of extinction in the wild"
    ],
    "example": "The Royal Bengal Tiger of Sundarbans is a critically endangered species.",
    "useCase": "Habitat loss has placed countless wildlife species on the endangered list.",
    "textbookUseCase": "Lesson 3 highlights the urgent necessity of protecting endangered global wildlife.",
    "synonyms": "threatened, vulnerable, dying out, at risk, imperiled",
    "unitNumber": 12,
    "unit": "Unit 12: Environment and Nature",
    "lesson": "Lesson 3: Endangered Species",
    "page": 230,
    "printedPage": 224,
    "level": "Basic",
    "antonyms": "abundant, thriving, flourishing, safe, secure"
  },
  {
    "id": "v1204",
    "word": "sustainability",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "টেকসই উন্নয়ন, পরিবেশবান্ধব স্থায়িত্ব",
    "correctDefinition": "the ability to maintain ecological balance by avoiding depletion of natural resources",
    "options": [
      "the ability to maintain ecological balance by avoiding depletion of natural resources",
      "excessive consumption of fossil fuels",
      "the abandonment of clean solar energy",
      "the rapid destruction of rainforests"
    ],
    "example": "Environmental justice demands global sustainability and renewable energy policies.",
    "useCase": "Sustainable agriculture ensures food security for future generations.",
    "textbookUseCase": "Lesson 4 discusses climate justice, resource equity, and ecological sustainability.",
    "synonyms": "ecological balance, renewable practice, durability, conservation",
    "unitNumber": 12,
    "unit": "Unit 12: Environment and Nature",
    "lesson": "Lesson 4: What is Environmental Justice?",
    "page": 236,
    "printedPage": 230,
    "level": "Intermediate",
    "antonyms": "depletion, destructiveness, wastefulness, unsustainability"
  },
  {
    "id": "v1205",
    "word": "naturalism",
    "partOfSpeech": "noun (বিশেষ্য)",
    "bangla": "প্রকৃতিবাদ, প্রকৃতির নিয়ম মেনে চলা",
    "correctDefinition": "an approach living in harmony with nature rather than forcing mechanical control",
    "options": [
      "the total reliance on computer algorithms",
      "an approach living in harmony with nature rather than forcing mechanical control",
      "the heavy use of chemical pesticides in soil",
      "the building of concrete skyscrapers in forests"
    ],
    "example": "Masanobu Fukuoka advocated natural farming and philosophical naturalism.",
    "useCase": "Naturalism in agriculture respects the natural ecosystem and microbial life.",
    "textbookUseCase": "Lesson 5 reflects on Masanobu Fukuoka's natural farming philosophy and scientific limits.",
    "synonyms": "natural harmony, organic philosophy, ecological realism",
    "unitNumber": 12,
    "unit": "Unit 12: Environment and Nature",
    "lesson": "Lesson 5: Limits of the Scientific Method",
    "page": 241,
    "printedPage": 235,
    "level": "Advanced",
    "antonyms": "artificiality, mechanical control, industrialization"
  }
];